baseURL = "https://rdpalacio.co/"
languageCode = "en-us"
copyright = "Attribution 4.0 International (CC BY 4.0)"
title = "Ruben Dario Palacio"
theme = "hugo-theme-notrack"
newContentEditor = "nvim"
mainSections = ["essays"]
paginate = 4
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  author = "Ruben Dario Palacio"
  siteHeading = "Ruben Dario Palacio" # defaults to author
  showBlogLatest = true
  mainSections = ["essays"]
  showTaxonomyLinks = false
  nBlogLatest = 10 # number of blog post om the home page
  blogLatestHeading = "Ruben's Essays"

  [params.social]
    researchgate = "Ruben_Dario_Palacio"
    googlescholar = "user=jRGXJK4AAAAJ&hl=en"
    github = "rdpalacio/"
    twitter = "rdpalacio"
    email = "rdpalacio@ecotonos.org"
    
[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  essays = "/essays/:year/:month/:slug"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = [ "RSS", "HTML" ]
  section = [ "HTML" ]
  taxonomyTerm = [ "HTML" ]
  taxonomy = [ "HTML" ]

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/RSS"
  baseName = "feed"
